### ISSUE TITLE
update instructions

### ISSUE THREAD

**Issue by joelpick** [EIvimeyCook/shinyDigitise#10]
need to make sure instructions are much more helpful and appear when they are meant to

**Comment by joelpick** [comment]
instructions don't come up at the beginning

**Comment by EIvimeyCook** [comment]
This is caused by L221 and L522. Removed

**Comment by EIvimeyCook** [comment]
Could we change instructions to these?

https://shiny.rstudio.com/articles/notifications.html

Would free up plotting space....
