### ISSUE TITLE
where have the images gone?

### ISSUE THREAD

**Issue by joelpick** [EIvimeyCook/ShinyDigitise#5]
lost tickes and crosses and shinydigitise logo

**Comment by EIvimeyCook** [comment]
So i think this is caused due to the runApp call being at a different level to the www folder.

I've sorted out why it doesn't load on mine  and switched to using renderImage and text for the logo/title text.

You may need to sort it on your own pc? I can see the crosses and ticks.

**Comment by joelpick** [comment]
Need a solution that will work on everyone computer though. Moving the www folder into the r folder doesn’t seem to work. Render image is used for the crosses and ticks but that doesn’t work either. Strange that it wasn’t working on yours and now is and the reverse on mine 

>

**Comment by joelpick** [comment]
I'll try this once its a package https://stackoverflow.com/questions/54993463/include-image-in-r-packages

**Comment by joelpick** [comment]
for noe I have replaced the images with words to get that fully functional (02f9f5bb). then we can replace with images

**Comment by EIvimeyCook** [comment]
any easier solution could be to have button with icons for success/failure - ie thumbs up or down? Could be easy to implement and won't require external images. 

shinyWidgets have icons for instance...

**Comment by joelpick** [comment]
Not going to help with the logo thought - I think weight be able to use emojis for the tick and cross - will try it
