### ISSUE TITLE
Can still add or delete row when no row is selected.

### ISSUE THREAD

**Issue by EIvimeyCook** [EIvimeyCook/ShinyDigitise#7]
Still allows for plotting of points and deleting based on the previously clicked row.

**Comment by joelpick** [comment]
More details? What did you click

**Comment by EIvimeyCook** [comment]
Selected a row - then deselected by clicking it again. Then press delete or add points.

**Comment by joelpick** [comment]
Hmm weird - didnt we resolve that yesterday?

**Comment by EIvimeyCook** [comment]
Yeh! Thought so! I pulled the latest version...

So it still works after you've clicked two points for a group. This is when you're about to click two points for a group...

**Comment by EIvimeyCook** [comment]
Thin this is now solved.
