### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by joelpick** [EIvimeyCook/shinyDigitise#8]
use plot_brush to get zoom coords to zoom in, and plot_dblclick to zoom out. update internal_redraw to have a zoom argument, and then plot given coords

**Comment by joelpick** [comment]
first version implemented in b395830. problem is that click and brush are confused, so zooming in click mode also results in a click which we dont want.

solution maybe here https://jokergoo.github.io/2021/02/20/differentiate-brush-and-click-event-in-shiny/

also would be clear brushed area - maybe see https://stackoverflow.com/questions/30588472/is-it-possible-to-clear-the-brushed-area-of-a-plot-in-shiny

**Comment by joelpick** [comment]
clearing brushed area solved cd4d68c

**Comment by EIvimeyCook** [comment]
Zoom works - you use the brush then click zoom and it'll zoom in. Clicking zoom again returns the plot to the original zoom level. 

The zoom option is now disabled when in calibration mode.
